[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

# Environment variables should be set in Netlify dashboard
# Do not put sensitive data here in a public repository
# [build.environment]
#   REACT_APP_API_URL = "your-backend-url"
#   REACT_APP_DEMO_EMAIL = "your-demo-email"
#   REACT_APP_DEMO_PASSWORD = "your-demo-password"