# Netlify configuration file
[build]
  # Directory to run the build command in (root of monorepo)
  base = ""
  
  # Build command - installs dependencies then builds
  command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "client/build"

# Environment variables
[build.environment]
  NODE_VERSION = "16"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200