# Netlify configuration file
[build]
  # Directory to run the build command in
  base = "client"
  
  # Build command - installs dependencies then builds
  command = "npm install && npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "build"

# Environment variables
[build.environment]
  NODE_VERSION = "16"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200